spring.application.name=demo_logging
server.port=8090

#\u5F00\u542F\u9759\u6001\u8D44\u6E90\u6620\u5C04
spring.web.resources.add-mappings=true

#\u8BBE\u7F6E\u7F13\u5B58
spring.web.resources.cache.period=3600

spring.web.resources.cache.cachecontrol.max-age=7200




